[build]
target = "x86_64-loony_os.json"

[target.x86_64-loony_os]
linker = "rust-lld"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
